# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objectrep.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fobjectrep.proto\x12\x02jv\"W\n\x0fObjectCoordData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\x05\x12\x0c\n\x04x_2d\x18\x03 \x01(\x02\x12\x0c\n\x04y_2d\x18\x04 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x05 \x01(\x02\"a\n\rObjectRepData\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x02\x12$\n\x07objects\x18\x03 \x03(\x0b\x32\x13.jv.ObjectCoordDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objectrep_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECTCOORDDATA']._serialized_start=23
  _globals['_OBJECTCOORDDATA']._serialized_end=110
  _globals['_OBJECTREPDATA']._serialized_start=112
  _globals['_OBJECTREPDATA']._serialized_end=209
# @@protoc_insertion_point(module_scope)
