---

driver:
    device: mps  # cpu, mps, or cuda
    output_to: none  # socket, file, or none
    serial_type: struct  # struct or protobuf
    object_model_name: yolo11
    vda_model_name: vits
    chkpts_folder: ./checkpoints
    retain_frames: 30
    object_buffer_size: 0
    frame_buffer_size: 1
    warmup_frames: 30
    camera_index: 0
    binocular: false
    frame_skip: 0
    frame_rate: 30
    show_det: true
    depth: true
    metric: true  # enables absolute/metric depth

object:
    tracker: bytetrack.yaml  # botsort.yaml or bytetrack.yaml
    conf: 0.25
    iou: 0.7
    half: false  # half-precision inference

mono:
    fp32: true  # fp32=False causes a black output and NaN values in model

stereo:
    num_disparities: 96  # 16 * 6, must be divisible by 16
    block_size: 11  # odd number >= 5
    min_disparity: 0.0
    calibration_data: camera_calibration.yaml
    left_sensor_id: examples/videos/left.mp4  # if set to string then can open filepath
    right_sensor_id: examples/videos/right.mp4  # if set to string then can ope filepath

gstreamer:
    sensor_mode: 3  # (1280x720, 59.9999 fps)
    capture_width: 1280
    capture_height: 720
    display_width: 1280
    display_height: 720
    framerate: 30
    flip_method: 2