---

driver:
    device: cuda  # cpu, mps, or cuda
    output_to: socket  # socket, file, or none
    serial_type: struct  # struct or protobuf
    object_model_name: yolo11
    det_whitelist: [0]  # refer to yolo_utils.py for label list
    vda_model_name: vits
    chkpts_folder: ./checkpoints
    retain_frames: 30
    object_buffer_size: 1
    frame_buffer_size: 1
    warmup_frames: 30
    camera_index: 0
    binocular: false  # allows for two camera's to be used, also uses GStreamer pipeline
    frame_skip: 0
    frame_rate: 30
    show_det: true
    depth: true
    metric: false  # enables absolute/metric depth
    multi_object: false  # allows for multiple objects to be sent, if disabled sends closest
    use_kalman: false  # enables Kalman filter for coordinate smoothing

object:
    tracker: bytetrack.yaml  # botsort.yaml or bytetrack.yaml
    conf: 0.25
    iou: 0.7
    max_det: 10
    half: false  # half-precision inference

mono:
    fp32: true  # fp32=False causes a black output and NaN values in model

stereo:
    method: sgbm  # options: sgbm (default, more accurate, slower), bm (faster, simpler), vpi (SGBM using NVIDIA VPI, faster, only CUDA)
    num_disparities: 32  # max disparity - min disparity, must be divisible by 16
    block_size: 3  # matched block size, odd number >= 1, typically 3-11
    min_disparity: 0  # min disparity value, adjust if rectification shifts images
    # P1: null  # smoothness penalty for ±1 disparity change; defaults to 8*1*block_size^2
    # P2: null  # smoothness penalty for >1 disparity change; defaults to 32*1*block_size^2, must be > P1
    disp12_max_diff: 1  # max left-right disparity diff (pixels), non-positive to disable
    pre_filter_cap: 0  # clips x-derivative to [-val, val] for Birchfield-Tomasi cost
    uniqueness_ratio: 5  # min margin (%) best cost must win by, typically 5-15
    speckle_window_size: 100  # max smooth region size for speckle filtering, 0 to disable, typically 50-200
    speckle_range: 2  # max disparity variation in connected component, implicitly *16, typically 1-2
    max_depth: 10000.0  # max depth (mm), points beyond are zeroed
    calibration_data: camera_calibration.yaml
    left_sensor_id: 1  # if set to string then can open filepath
    right_sensor_id: 0  # if set to string then can open filepath
    sample_method: gauss
    wls_filter: true
    wls_lambda: 8000  # Regularization for WLS smoothness
    wls_sigma: 1.5  # Sensitivty of filter to edges (0.8 - 2.0)
    med_filter: true  # median blur filter
    ksize: 3  # must be odd number

gstreamer:
    sensor_mode: 4  # (1280x720, 59.9999 fps)
    capture_width: 1280
    capture_height: 720
    display_width: 320
    display_height: 180
    flip_method: 2